project_name: build-tools

before:
  hooks:
  - docker login -u sparetimecoders -p {{ .Env.DOCKERHUB_PASSWORD }}

env:
  - CGO_ENABLED=0

builds:
  - id: build
    main: ./cmd/build/build.go
    binary: build
    flags:
      - -tags=prod
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: push
    main: ./cmd/push/push.go
    binary: push
    flags:
      - -tags=prod
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: deploy
    main: ./cmd/deploy/deploy.go
    binary: deploy
    flags:
      - -tags=prod
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: kubecmd
    main: ./cmd/kubecmd/kubecmd.go
    binary: kubecmd
    flags:
    - -tags=prod
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: promote
    main: ./cmd/promote/promote.go
    binary: promote
    flags:
    - -tags=prod
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    ids: [ "build", "push", "deploy", "kubecmd" ,"promote" ]
    image_templates:
    - "buildtool/{{ .ProjectName }}:latest"
    - "buildtool/{{ .ProjectName }}:{{ .Tag }}"
    - "buildtool/{{ .ProjectName }}:{{ .Version }}"

brews:
  - name: build-tools
    repository:
      owner: buildtool
      name: homebrew-taps
    folder: Formula
    install: |
      bin.install "build"
      bin.install "push"
      bin.install "deploy"
      bin.install "kubecmd"
      bin.install "promote"
    commit_author:
      name: peter-stc
      email: peter@sparetimecoders.com
    homepage: "https://buildtools.io/"

archives:

- id: build-tools
  name_template: >-
    {{- .ProjectName }}_
    {{- .Version }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native
