baseURL = "https://buildtool.github.io/"
languageCode = "en-us"
title = "build-tools"
copyright = "© 2019 buildtool"
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[params]
name = "build-tools"
description = "desc"
logo = "https://github.com/buildtool.png"
ghdocsrepo = "https://github.com/buildtool/build-tools/edit/master/www"