name: docs

on:
  push:
    tags:
      - 'v*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: 3.x
      - name: install mkdocs
        run: |
          pip install mkdocs-material
          pip install mkdocs-minify-plugin
      - name: build site
        run: |
          cd www
          mkdocs build
      - name: htmltest
        run: |
          cd www
          curl https://htmltest.wjdp.uk | bash
          ./bin/htmltest -c htmltest.yaml

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./www/site
          publish_branch: main
          external_repository: buildtool/buildtool.github.io
