name: "golang-ci-lint"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'www/**'
      - '*.md'
      - '.editorconfig'
      - 'LICENSE'
      - 'install.sh'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'www/**'
      - '*.md'
      - '.editorconfig'
      - 'LICENSE'
      - 'install.sh'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: 'true'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout=5m
