name: "golang-vulnerabilities"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'www/**'
      - '*.md'
      - '.editorconfig'
      - 'LICENSE'
      - 'install.sh'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'www/**'
      - '*.md'
      - '.editorconfig'
      - 'LICENSE'
      - 'install.sh'

jobs:
  golangci:
    name: golang-vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: opzkit/govulncheck-action@914e0763397999f9c7cc3be08b56787060f36dd8 # v1.2.0
        with:
          go-version-file: 'go.mod'
          check-latest: 'true'
